defmodule Malin.Repo.Migrations.UpdatePosts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:users, [:id], name: "users_primary_key_index", prefix: "accounts")

    create unique_index(:categories, [:id],
             name: "categories_primary_key_index",
             prefix: "categories"
           )
  end

  def down do
    drop_if_exists unique_index(:categories, [:id],
                     name: "categories_primary_key_index",
                     prefix: "categories"
                   )

    drop table(:tokens, prefix: "accounts")

    drop_if_exists unique_index(:users, [:id],
                     name: "users_primary_key_index",
                     prefix: "accounts"
                   )
  end
end
