defmodule Malin.Repo.Migrations.AddIconToContentItems do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:content_items) do
      add :icon, :text
    end
  end

  def down do
    alter table(:content_items) do
      remove :icon
    end
  end
end
