defmodule Malin.Repo.Migrations.ChangeDefaultUserApplicant do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users, prefix: "accounts") do
      modify :role, :text, default: "applicant"
    end
  end

  def down do
    alter table(:users, prefix: "accounts") do
      modify :role, :text, default: "user"
    end
  end
end
