defmodule Malin.Repo.Migrations.AddNameToUser do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users, prefix: "accounts") do
      add :first_name, :text
      add :last_name, :text
    end
  end

  def down do
    alter table(:users, prefix: "accounts") do
      remove :last_name
      remove :first_name
    end
  end
end
