defmodule Malin.Repo.Migrations.AddCourseToUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users, prefix: "accounts") do
      add :course, :text, default: "open"
    end
  end

  def down do
    alter table(:users, prefix: "accounts") do
      remove :course
    end
  end
end
