defmodule Malin.Repo.Migrations.AddAnalytics do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute "CREATE SCHEMA IF NOT EXISTS analytics"

    create table(:pageviews, primary_key: false, prefix: "analytics") do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :path, :text, null: false
      add :referrer, :text
      add :user_agent, :text
      add :country, :text
      add :browser, :text
      add :os, :text
      add :viewed_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:pageviews, prefix: "analytics")
  end
end
