defmodule Malin.Repo.Migrations.AddApplicationToUser do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users, prefix: "accounts") do
      add :application_note, :text
    end
  end

  def down do
    alter table(:users, prefix: "accounts") do
      remove :application_note
    end
  end
end
